### ISSUE TITLE
Reward Voting May 001

### ISSUE THREAD

**Issue by mnzone-dev** [rupaya-project/proposals#1]
## Requested funds

* **100,000** RUPX coins which represent **13%** of the monthly governance budget.
It will be paid to the `7KT6fvNDEZTF9hTPGVPjAnHdgR8Fj5FdeN` address when we reach block 129,600 (around May 13, 2018) if MasterNode owners support it with `Yes` votes.
* **50** RUPX to cover the proposal creation fee

## What are the funds for

The idea is to reward community governance participation, which will increase adoption and reduce the risk of governance being misused by investors that control lots of MasterNodes, _whales_ or shared masternode operators.

The funds will be split between MNs addresses that have been used to vote during the budget cycle. Payment will be sent to the public address where normal MasterNode rewards go.

Say there are **1000** MasterNodes in the network. To keep it simple, **320** of them vote on all proposals. **20** of these have a "red" port on `mn.rupx.io`, meaning they don't help the network. These will not receive vote rewards. So, we are left with **300** MasterNodes, each getting a **332** RUPX "good citizen" reward. For this proposal, we are not going to consider how many votes a node has placed. One vote is enough to get a chunk of this proposal budget.

The distribution of the funds will be done via a script that calls the `mn.rupx.io` API, loops over each masternode that has voted at least once and sends the voting reward.
The `Voting` column on http://mn.rupx.io indicates if your MasterNode has voted or not. Keep those little 🚀 🚀 🚀 coming.

Welcoming any thoughts or comments, thank you.

## Proposal creator Discord user
`mn.zone_dev#7125`

**Comment by glomin** [comment]
I think `reimburse proposal fees` would be more precise in the title rather than `pay`.

**Comment by tech1e** [comment]
Updated, thanks for the feedback @glomin. 
I also changed `Incentivize` to `Reward`in the title

**Comment by rupaya-project** [comment]
Giving MasterNodes incentives will greatly improve the number MN's participating in the voting process. Good Proposal

**Comment by tech1e** [comment]
Let's see if it's being voted by MasterNodes :)

**Comment by tech1e** [comment]
The initial proposal had a Reimburse proposal fees element to it. I removed it to keep this focused. Removed glomin's comment as well as it was for that idea.

**Comment by mnzone-dev** [comment]
The proposal is ready to be stored in the `final` directory.
Please provide the permanent link in order to add it in the blockchain.

**Comment by velkgrem** [comment]
This is an excellent proposal. Really like the idea of rewarding MNs that vote. I could see a case for making this a reoccurring proposal as well.

**Comment by gabipavel** [comment]
This will work nicely :)

**Comment by zmulk** [comment]
I like it!

**Comment by reefs** [comment]
Thank you, @mnzone-dev.

Now that the text is stored in the final directory, you can use this URL in your proposal submission:

https://github.com/rupaya-project/proposals/blob/master/final/001_reward_voting_may.md

... or this short link to it: 

https://git.io/vpsKP

**Comment by mnzone-dev** [comment]
Thank you, I submitted the proposal and it's live at http://mn.rupx.io/proposals.html

If it's passing, I'll post here how the rewards have been distributed.

**Comment by Wall-ETcoin** [comment]
This sounds cool.
Hope it passes the voting.

And it has a good idea that the MNs who have red port (do not help the network) are excluded from the rewards...

**Comment by rhanxerox** [comment]
Good proposal, Hope it passes the voting

**Comment by mnzone-dev** [comment]
Someone mentioned excluding the nodes that are on the old `4.0.0` wallet, but I don't see any of the 214 MNs that voted on that. Maybe they can't vote or they are just no very active... Will see in a few days.

**Comment by mnzone-dev** [comment]
I've started pushing out rewards with a script, but had to introduce some delays (20s) now between the transaction to avoid the "Insufficient funds" error from the wallet.
I'll post here the full list of addresses and tx ids in the morning when I wake up.

**Comment by mnzone-dev** [comment]
Left the script overnight and it appears that all MN addresses from above have been paid. This is the output: [paid-addrs.txt](https://github.com/rupaya-project/proposals/files/1999572/paid-addrs.txt)

**Comment by mnzone-dev** [comment]
Thank you everyone that participated with comments here and for voting on proposals. I'll close this ticket now.
