### ISSUE TITLE
Marketing: Twitter Giveaway

### ISSUE THREAD

**Issue by NerdyUser** [rupaya-project/proposals#14]
## Requested funds

- 5.000 RUPX for a Twitter giveaway. It will be paid to an address of me `7ADejfYMzo649dxJ58rUqxEWkUXH3VPpWS` if MN owners support it with `Yes` votes.
- 50 RUPX to cover the proposal creation fee

## Describe your proposal

Biggest reason for this giveaway is pretty straight forward: getting more followers on the official [Twitter](https://twitter.com/RupayaCoin) account. This will lead in the future to more retweets, likes, followers, views and investors.

I would propose to hold 5 rounds in which everyone can participate. Each round will be a tweet from the official [Twitter](https://twitter.com/RupayaCoin) account containing the giveaway of 1.000 RUPX (~$130 at this moment) with the requirements. When a tweet has been tweeted inform all Discord members with an @everyone tag and a link to the tweet (=else this marketing will fail; Twitter account has too low response at the moment).

Requirements before we determine a winner:
* Tweet needs at least 200 retweets and at least 2 days online before the round ends (=14 day Twitter campaign)
* Winner needs to:
--> Be a follower of the official [Twitter](https://twitter.com/RupayaCoin) account
--> Have retweeted that tweet
--> Have liked the tweet

[TWrench](https://twren.ch/) (=example) picks the winner, mayby a printscreen can be shared on Twitter to announce the winner and to ask the winner to contact RupayaCoin. RupayaCoin can contact me on Twitter (or Discord) with the address of the winner. A TxID will be answered to verify the transfer.

If a round takes too long / don't reach 200 retweets the 1.000 RUPX will be send to my Discord account and will get soaked `.soak 1000 ==> soaks 1000 RUPX over all online users` at a random time. 

## Proposal creator Discord user

NerdyUser#9077

**Comment by NerdyUser** [comment]
Feel free to correct my grammar.

**Comment by BlockchainBrain** [comment]
I have a few questions for you:

1) How is a winner determined?  
2) Who is creating the content of the Tweet?  Getting a group of followers to retweet something is not nearly as valuable as getting them to retweet useful content, so there needs to be some basis for the types of information in the Tweet.  Or is the tweet just that it is part of a contest to generate tweets and the person who gets the most retweets wins?
3) If there is a tie, who determines the tie-breaker?
4) If no one achieves the 200 tweets within the time period, wouldn't it make more sense to continue to hold those funds for a new round so the campaign can continue without needing additional funds?

**Comment by pslobo** [comment]
This falls squarely in the Marketing camp and given there is already a budget for that I feel it would make more sense. In regard to what @BlockchainBrain said, retweeting for the sake of retweeting is pointless. We want valid content share since that is what will ultimately drive interest and in that regard there is already the 10K Comeptition. It's better to get twitter followers organically than simply so they can win 1000 RUPX which they will then most likely dump if they don't have interest in the project.
