### ISSUE TITLE
no nodes / ip in .conf file in OSX wallet

### ISSUE THREAD

**Issue by elekim** [rupaya-project/proposals#2]
## after downloading the OSX wallet i checked the .conf file for the nodes. list is empty. therefore my wallet can‘t connect or sync.
could you provide new users with that list to copy paste or have a .conf ready for download on github?
if it already exists, please point me in the correct direction.

thanks in advance!

**Comment by rupaya-project** [comment]
Nodes will be hardcoded in the next release for now please use `# Seeds DNS updated daily with up to 24 reachable node IPs:
addnode=rupx.seeds.mn.zone
# Static list of reachable node IPs:
addnode=45.63.67.204:9020
addnode=195.201.87.66:9020
addnode=198.46.168.26:9020
addnode=80.82.215.187:9020
addnode=199.247.23.205:9020
addnode=45.77.108.189:9020
addnode=199.247.15.121:9020
addnode=62.77.158.138:9020
addnode=198.13.39.55:9020
addnode=140.82.33.183:9020
`
