### ISSUE TITLE
Community Support 003

### ISSUE THREAD

**Issue by mnzone-dev** [rupaya-project/proposals#3]
## Requested Funds

* One time proposal of **30,000** RUPX
* **50** RUPX to cover the proposal submission fee 

Paid to one of my addresses `76tKZXUVoZx4ZuHGjthugt9pFiBHRSfFfo`

## Describe your proposal

The coins will be distributed to five users that are the most active and helpful in the community.
For example: moderators, tech support in Discord, Bitcointalk, Proposals repo, etc

If this proposal passes, we can have a Discord announcement with the nominees. Each will have an emoji number attached. Top five will be picked based on the number of emoji votes. 

The winners will receive a 6,000 RUPX reward for their dedication to the project and community.
They could also receive a special Discord role(Community Superstar, or similar) for the next month.
The aim is to reward good behavior with a good amount of RUPX!

If this is a success, we can have it as a monthly proposal, starting from the next budget cycle.

## Proposal creator Discord user:
`mn.zone_dev#7125`

**Comment by theDavidCoen** [comment]
Good proposal. If the amount is not reachable we could think about a first, second and third place with for ex. 10k Rupx (1), 5k (2), and 2.5k (3).

**Comment by mnzone-dev** [comment]
The amount is always reachable David, if the proposal is voted, 30k RUPX will be minted into the address specified.

**Comment by theDavidCoen** [comment]
right

**Comment by gabipavel** [comment]
This is very well thought my friend! It should boost up the activity! Good luck all!

**Comment by mnzone-dev** [comment]
I hear you @00newen. This is a one time proposal with payment estimate in mid May. If the price doubles since then, we can reduce it to 5000k RUPX for the next budget. Or have it every 2-3 months.

I think it's an experiment worth trying. A helping community in this space boosts confidence and growth. These things are crucial in these early days of high coinbase inflation.

**Comment by mikkyrod1** [comment]
Excellent proposal, an active community speaks well of the project before new investors.

**Comment by mnzone-dev** [comment]
How about splitting this 30k amount into 5 instead of 3 prizes? This way we can reward more moderators/helpers

**Comment by velkgrem** [comment]
I'd recommend updating to reward 5 prizes. That's a great idea and will help spur people to stay active even if they don't think they are the top one or two.

**Comment by mnzone-dev** [comment]
I was thinking the same, thanks for confirming Velk.
I'll update the proposal

**Comment by theDavidCoen** [comment]
Agree with Velk

**Comment by rupaya-project** [comment]
Good stuff, I think we can start voting on this now!

**Comment by 00newen** [comment]
Do we want to have some conditions or guidelines in this?

Time wise or amount of texts/posts. Or something.

**Comment by rupaya-project** [comment]
Good point @00newen, what are the conditions to qualify for a reward?

**Comment by mnzone-dev** [comment]
Anyone qualifies as long as it receives enough votes to make it in top 5. We can start creating the list here of nominees.

**Comment by mnzone-dev** [comment]
The proposal has been committed into the `final` directory and will soon be placed in the blockchain:
`https://github.com/rupaya-project/proposals/blob/master/final/003_community_support.md` with shortlink: `https://git.io/vplqy`

**Comment by mnzone-dev** [comment]
Changed the label as the proposal is up for voting

**Comment by mnzone-dev** [comment]
The proposal has been honored by the blockchain:

https://whereismy.rupx.io/address/76tKZXUVoZx4ZuHGjthugt9pFiBHRSfFfo

Will sync with the team and create a plan for identifying the 5 winners.

**Comment by mnzone-dev** [comment]
In order to bring closure to this proposal, I'm collecting the nominees that users will be asked to vote for. I had a quick scan through the discord channels to look for the most active helpers and came up with this list myself. It's sorted alphabetically:
```
David Coen#7930
Gabi#5533
gdiscord#2118
GoodTimes#0673
Kasparov#7537
Pooiz#5098
Reefy#0384
tooshameless239#8004
velk#8724
```
Please comment below with other nominees you think should be included in

**Comment by theDavidCoen** [comment]
Thank you for the nomination, I really appreciate!

**Comment by pslobo** [comment]
Thanks @mnzone-dev appreciate it. I guess it will be up to the community to vote now. Any ideas on how voting should work?

**Comment by bjorntheart** [comment]
Thanks @mnzone-dev

**Comment by mnzone-dev** [comment]
@pslobo at the moment I'm thinking a discord announcement with emoji for each nominee. It's a simple way for people to vote on one or multiple people

**Comment by gabipavel** [comment]
Good idea. Should work. I dont think it will end in blood. Best guys here

**Comment by pslobo** [comment]
@mnzone-dev yeah, that could work and makes sense

**Comment by mnzone-dev** [comment]
I reached out to the five winners, got their Rupaya addresses and sent 6000 RUPX each (20% of the proposal) 

TX IDs:
```
4f8c7129ac752c9d180226c82f1f8c12916a15fadacd48010c05b6f3fad34581
e2aa162338694ed05830ceed213ba58b98a3d5948aa071c76d33d9aad76ff598
9fd9024e991ca15417204611fec26b4f43c876b1cd3e108bf63c609a177cc61e
67c60533f9aef0c6258e25eafd136ba978814a75aed532e9c38ebbd614d428fc
77513fd19e32bea6bc593814d43ec4e0c04b6def5fd11dadcc4c146d0513f019
```

Congratulations and thank you for your contributions to the project and community!
