### ISSUE TITLE
List on Bigger Exchanges

### ISSUE THREAD

**Issue by mnzone-dev** [rupaya-project/proposals#4]
## Describe your proposal

This is a monthly recurrent proposal to build up a RUPX budget that can be used to list Rupaya on bigger and better exchanges. 
Ideally, the listing fee will be in RUPX so we don't have to sell the coins on the market for BTC/ETH/etc

Allocate between 10-20% of the monthly governance budget for this.

## Requested Funds in RUPX

100,000 RUPX per month

**Comment by theDavidCoen** [comment]
Totally agree with this proposal and I would like to improve it with a more specific proposal about listing.

**Comment by gabipavel** [comment]
Not sure if listing rupx on more exchanges will have a significant impact in terms of price/coin, but if the community really wants to see it done, then I will make sure to contribute.

**Comment by rupaya-project** [comment]
Most exchanges will only accept payment in BTC. The next viable option for us is coinexchange their listing fee is about 4BTC

**Comment by 00newen** [comment]
I agree we should be on more exchanges. Having to open an account in one new exchange you don't have just to buy one more coin makes people think twice before going in and buying the coin. It does for me at least.

Having said this, I have no experience nor knowledge on how getting listed in exchanges works so we really need someone with experience/knowledge on this to improve the proposal to make it into something that could actually work.

**Comment by mikkyrod1** [comment]
it is a fact to incorporate the currency to new exchanges but not indiscriminately, it should be selected in what exchange is suitable for the project and consolidates its growth.

**Comment by darioxx979** [comment]
Totally agree :) we must grow

**Comment by Gambobit** [comment]
My only concern is are we up to the point of getting listed in other exchanges? I saw above that to get into coinexchange we needed to pay 4BTC . I know it is comfortable to be able to transact all your cryptos in your favorite exchange, but is this the best option now for the project? IMO the aim should be the top exchanges used in South Asia market (RUPX target) if we're not listed there yet.

**Comment by shailysingh1975** [comment]
BITINIDIA is very soon going to launch its global exchange. They have rebranded as "Blockonix". accepting listing at the moment. I think we should try that. 

https://docs.google.com/forms/d/e/1FAIpQLSePedmUAtQfr_KpNKQrP5Q63pAhGa_4wdTBE4jgXJCL8a5eAw/viewform

**Comment by mnzone-dev** [comment]
Closing this proposal draft for now. We don't have enough volume at the moment to convert 100s K of RUPX into BTC to pay for the bigger exchanges. At this point, we either find exchanges willing to list us in exchange for RUPX coins or wait for RUPX price and volume to increase so that we can generate BTC funds without crashing the market trying to sell RUPX acquired by such proposal.
