### ISSUE TITLE
Block Explorer - PoS Difficulty Chart 005

### ISSUE THREAD

**Issue by reefs** [rupaya-project/proposals#9]
## Requested funds

* **10,000** RUPX coins which represent 1.3% of the monthly governance budget. It will be paid as a one-time payment to my `7Asm8uabqUAF17KhuNqX7ARdEFEY6XSBEG` address when we reach block 129,600 (around May 13, 2018) if MasterNode owners support it with `Yes` votes.
* **50** RUPX to cover the proposal creation fee

## Describe your proposal

The blockchain has always been an obscure concept for most of us. The issue lies in the lack of visibility and the difficulty to navigate through the blocks to see what's important. It is time-consuming and error-prone to try and see any type of trends or major changes in the patterns to be able to make projections.

I am proposing to add charts (line, column, pie, etc.) to our current block explorer (https://whereismy.rupx.io) under a new menu item (*Charts*) in order to bring that visibility and transparency. It will also enable us to dissect more easily what is going on within the blockchain. If this idea is positively received, this proposal will be part of a series of proposals, one per chart.

So for the current proposal, I am planning to add a **Proof-of-Stake (PoS) Difficulty** as a line graph. This is useful for judging the current state of the chain from a staking perspective when considering the network weight and total supply.

To support this proposal I have built a mock-up on my local version of the Rupaya block explorer:

![image](https://user-images.githubusercontent.com/36220369/39401037-265c3752-4af1-11e8-995c-80de90dc8da1.png)

Here are other examples of graphs we can work on for future proposals:

* *Number of Transactions per Block*
* *Address Growth*
* *zRUPX Supply Growth*
* *zRUPX Denomination Distribution at Block*
* *RUPX vs zRUPX Dominance*
* *Orphan Blocks Count*
* *Block size (in bytes) per Block*
* feel free to suggest others in the comments and we'll discuss if it's technically feasible within the current block explorer implementation

If you are excited about these possible enhancements, there is no need to wait for the end of the superblock cycle (May 13th, 2018) to get them. If I see positive voting trends on this proposal I will start pushing the graph out (if done) to our official block explorer.

These graphs will help not just us, the current investors, but any potential future investor wanting to see trends, and, more importantly, a differentiating factor from the sea of coins out there. 

Help us keep the momentum up on the development side to have a match for our great marketing and community campaigns. :rocket:

## Proposal creator (Discord user)
`Reefy#0384` - official Rupaya block explorer developer and maintainer

**Comment by mnzone-dev** [comment]
Thank you @reefs, these are the sort of charts grown-up coins like Ethereum have. Makes it so much easier to look back in history, analyze trends and spot abnormalities. Let's get this one in and then discuss what the next chart should be. 👏

**Comment by theDavidCoen** [comment]
@reefs please go on with these improvement. They can give the explorer a more professional look and interesting for tech people.

**Comment by mnzone-dev** [comment]
I would love to see next the `RUPX vs zRUPX Dominance`. It would be an easy way to visualize:
1. Circulation growth based on block rewards
2. Circulation growth based on governance proposals getting in
3. Shift between RUPX and zRUPX total circulation

**Comment by mnzone-dev** [comment]
@reefs I saved the text of the proposal here:

`https://github.com/rupaya-project/proposals/blob/master/final/005_difficulty_chart.md`

with a short link you can use for the committed proposal:
`https://git.io/vp0cC`

You can use it to ask MNs the question, or you can refine it further. If the update is reasonable, it will be merged in the same file.

**Comment by reefs** [comment]
Due to the positive voting so far, we released the Proof-of-Stake Difficulty chart in advance. Users can take advantage of it even before the next superblock arrives (when passing proposals get paid).

Bonus features added since the proposal was written:
* zooming chart added to the top of the regular chart
* exporting the chart as PNG, JPG, SVG, PDF, CSV, XLXS, JSON
* annotating/editing the chart directly on the page
* printing the chart
* include 1440 blocks (a day's worth) of data in the chart

On to the next one!

**Comment by mnzone-dev** [comment]
Thank you again for the contribution, very useful!
Closing it and marking as `delivered`
